---

- name: Take down server and save world
  hosts: all
  gather_facts: no
  tasks:
    - name: take minecraft server down
      ansible.builtin.command: /usr/local/bin/docker-compose down
      args:
        chdir: /volume1/docker/minecraft-server
    - name: archive the world
      community.general.archive:
        path: /volume1/docker/minecraft-server/data/worlds/Bedrock level
        dest: /volume1/docker/minecraft-server/backup.gz
    - name: bring minecraft server up
      ansible.builtin.command: /usr/local/bin/docker-compose up -d
      args:
        chdir: /volume1/docker/minecraft-server
    - name: download backup
      ansible.builtin.fetch:
        src: /volume1/docker/minecraft-server/backup.gz
        dest: ~/minecraft-backups/backup{{ '%Y-%m-%d' | strftime }}.gz
        flat: true

