---
- name: take minecraft server down
  ansible.builtin.command: /usr/bin/docker-compose down
  args:
    chdir: /docker/minecraft-server
- name: archive the world
  community.general.archive:
    path: /docker/minecraft-server/data/worlds/Bedrock level
    dest: /docker/minecraft-server/backup.gz
- name: bring minecraft server up
  ansible.builtin.command: /usr/bin//docker-compose up -d
  args:
    chdir: /docker/minecraft-server
- name: download backup
  ansible.builtin.fetch:
    src: /docker/minecraft-server/backup.gz
    dest: ~/minecraft-backups/backup{{ '%Y-%m-%d' | strftime }}.gz
    flat: true

