---
- name: copy project files to nas
  ansible.builtin.copy:
    src: ../openssh/
    dest: /volume1/openssh/ansible
    owner: su-kadin
    group: users
    mode: '700'
  register: copyfile
- name: Creates config bindmount
  file:
    path: /volume1/openssh/config
    owner: su-kadin
    group: users
    mode: '700'
    state: directory
- name: Creates .ssh 
  file:
    path: /volume1/openssh/config/.ssh
    owner: su-kadin
    group: users
    mode: '700'
    state: directory
- name: copy project authorized_keys
  ansible.builtin.copy:
    src: ../authorized_keys
    dest: /volume1/openssh/config/.ssh/authorized_keys
    owner: su-kadin
    group: users
    mode: '700'
- name: copy bash profile
  ansible.builtin.copy:
    src: ../openssh/.profile
    dest: /volume1/openssh/config/.profile
    owner: su-kadin
    group: users
    mode: '700'
- name: Creates dir for custom scripting
  become: yes
  become_user: root
  file:
    path: /volume1/openssh/config/custom-custom-init
    owner: root
    group: root
    mode: '770'
    state: directory
- name: copy custom scripts
  become: yes
  become_user: root
  ansible.builtin.copy:
    src: ../openssh/scripts/
    dest: /volume1/openssh/config/custom-cont-init.d/
    owner: root
    group: root
    mode: '770'
- name: run docker-compose up -d
  ansible.builtin.command: /usr/local/bin/docker-compose up -d
  args:
    chdir: /volume1/openssh/ansible
