---
- name: copy docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /docker/minecraft-server/docker-compose.yml
    owner: ansible
    group: users
    mode: '666'
  register: copyfile
- name: run docker-compose up -d
  ansible.builtin.command: /usr/bin/docker-compose up -d
  args:
    chdir: /docker/minecraft-server