---
version: "2.1"
services:
  openssh-server:
    build: .
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - DOCKER_MODS=linuxserver/mods:code-server-docker
      - PUID=1026 # su-kadin
      - PGID=100 # users group
      # - TZ=Europe/London
      - PUBLIC_KEY_FILE=./authorized_keys
      - PASSWORD_ACCESS=false
      - USER_NAME=ansible
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /volume1/docker:/docker
    - /volume1/openssh/config:/config
    ports:
      - 2222:2222
    restart: unless-stopped
